version: '3'

services:
  
database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./database/mboardlogin.sql:/docker-entrypoint-initdb.d/mboardlogin.sql
  
  php:
    build: ./
    ports:
      - '80:80'

